import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import AppProvider from "@/components/appProvider";
import Splash from "@/components/splash";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <AppProvider>
        <body className={inter.className}>
          <Splash />
          <main>{children}</main>
          <Toaster />
        </body>
      </AppProvider>
    </html>
  );
}
